name: Frontend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Files
        run: ls -la

      - name: Validate HTML (optional)
        run: echo "Static site - no build needed"
